#!/bin/bash
# Fichero de instalacion para los scripts y ejemplos de buffer overflow

if [ "$EUID" -ne 0  ]
	then echo "Please run as root"
	exit
fi

cd
apt update
apt install -y python3-pip


echo [+] Installing pwntools
#pip install --upgrade pip
#apt remove -y python-capstone
pip install pwntools

echo [+] Updating GPG signatures
./firmas.sh

echo [+] Checking installed software
#apt update
apt install -y gcc
apt install -y gdb
apt install -y gcc-multilib  # Para la compilación con 32 bits
#ln -s gcc-6 /usr/bin/gcc 


echo [+] Installing rop-tool
cd
git clone https://github.com/t00sh/rop-tool.git ~/rop-tool
apt-get install -y libcapstone-dev
cd ~/rop-tool
make
export PATH=$PATH:/root/rop-tool

echo [+] Installing PEDA
git clone https://github.com/longld/peda.git ~/peda
echo "source ~/peda/peda.py" >> ~/.gdbinit

echo [+] Deactivating ASLR protection
echo 0 > /proc/sys/kernel/randomize_va_space
