#!/bin/bash
# Fichero de instalacion para los scripts y ejemplos de buffer overflow

if [ "$EUID" -ne 0  ]
	then echo "Please run as root"
	exit
fi



echo [+] Updating GPG signatures and packages
./firmas.sh
apt update

echo [+] Installing python3-pip
apt install -y python3-pip


echo [+] Installing pwntools
#pip install --upgrade pip
#apt remove -y python-capstone
pip install pwntools

echo [+] Checking installed software
#apt update
apt install -y gcc
apt install -y gdb
apt install -y gcc-multilib  # Para la compilación con 32 bits
#ln -s gcc-6 /usr/bin/gcc 


#echo [+] Installing rop-tool
#cd /home/kali
#sudo -u kali git clone https://github.com/t00sh/rop-tool.git /home/kali/rop-tool
#apt-get install -y libcapstone-dev
#cd /home/kali/rop-tool
#sudo -u kali make
#sudo -u kali export PATH=$PATH:/home/kali/rop-tool

echo [+] Installing PEDA
sudo -u kali git clone https://github.com/longld/peda.git /home/kali/peda
sudo -u kali echo "source ~/peda/peda.py" >> /home/kali/.gdbinit

echo [+] Deactivating ASLR protection
echo 0 > /proc/sys/kernel/randomize_va_space
