#!/bin/bash
# Installation file for buffer overflow scripts and examples

if [ "$EUID" -ne 0  ]
	then echo -e "\e[31m[+]\e[0m \e[32mPlease run as root\e[0m"
	exit
fi

VENV_DIR="../venv"
USER="gmacia"

echo -e "\e[31m[+]\e[0m \e[32mUpdating GPG signatures and packages\e[0m"
#./signaturesKali.sh
apt update

echo -e "\e[31m[+]\e[0m \e[32mChecking installed software\e[0m"
apt install -y gcc
apt install -y gdb
apt install -y gcc-multilib  # For compilation with 32 bits

# If needed install python
echo -e "\e[31m[+]\e[0m \e[32mInstalling python3-pip\e[0m"
apt install -y python3-pip

# Install virtualenv
echo -e "\e[31m[+]\e[0m \e[32mInstalling virtualenv\e[0m"
apt install -y python3-venv

read -p "Press [Enter] to continue..."

# Check if the virtual environment already exists
if [ -d "$VENV_DIR" ]; then
	read -p "The virtual environment '$VENV_DIR' already exists. Do you want to delete and recreate it? (y/n): " response
	if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
		rm -rf "$VENV_DIR"
		echo -e "\e[31m[+]\e[0m \e[32mDirectory '$VENV_DIR' deleted.\e[0m"
	else
		echo -e "\e[31m[+]\e[0m \e[32mOperation canceled. The script will terminate.\e[0m"
		exit 1
	fi
fi

# Create the virtual environment
echo -e "\e[31m[+]\e[0m \e[32mCreating virtual environment '$VENV_DIR'\e[0m"
sudo -u $USER python3 -m venv "$VENV_DIR"

# Activate the virtual environment
echo -e "\e[31m[+]\e[0m \e[32mActivating virtual environment '$VENV_DIR'\e[0m"
source "$(realpath $VENV_DIR)/bin/activate"

echo -e "\e[31m[+]\e[0m \e[32mInstalling pwntools\e[0m"
pip install --upgrade pip
pip install pwntools

echo -e "\e[31m[+]\e[0m \e[32mInstalling ropper\e[0m"
pip install ropper

read -p "Press [Enter] to continue..."

echo -e "\e[31m[+]\e[0m \e[32mInstalling GEF (GDB Enhanced Features)\e[0m"
sudo -u kali wget -O ~/.gdbinit-gef.py https://gef.blah.cat/py~
sudo -u kali echo "source ~/.gdbinit-gef.py" >> /home/kali/.gdbinit


