#!/bin/bash
# Installation file for buffer overflow scripts and examples

if [ "$EUID" -ne 0  ]
	then echo -e "\e[31m[+]\e[0m \e[32mPlease run as root\e[0m"
	exit
fi

########################
# PHASE 1
########################

echo -e "\e[32m------------------------------------------------------\e[0m"
echo -e "\e[31m[+]\e[0m \e[32mStarting phase 1. Updating of packages\e[0m"
echo -e "\e[32m------------------------------------------------------\e[0m"
echo -e "\e[31m[+]\e[0m \e[32mUpdating GPG signatures and packages\e[0m"
#./signaturesKali.sh
apt update

echo -e "\e[31m[+]\e[0m \e[32mChecking installed software\e[0m"
apt install -y gcc
apt install -y gdb
apt install -y gcc-multilib  # For compilation with 32 bits

# If needed install python
echo -e "\e[31m[+]\e[0m \e[32mInstalling python3-pip\e[0m"
apt install -y python3-pip

# Install virtualenv
echo -e "\e[31m[+]\e[0m \e[32mInstalling virtualenv\e[0m"
apt install -y python3-venv

echo -e "\e[31m[+]\e[0m \e[32mPhase 1 finished. Review logs to check for errors\e[0m"
read -p "Press [Enter] to continue..."

########################
# PHASE 2
########################


echo -e "\e[32m------------------------------------------------------\e[0m"
echo -e "\e[31m[+]\e[0m \e[32mStarting phase 2. Creating python virtual environment\e[0m"
echo -e "\e[32m------------------------------------------------------\e[0m"

# Check if the virtual environment already exists

REAL_USER=${SUDO_USER:-$USER}

VENV_DIR="../venv"

if [ -d "$VENV_DIR" ]; then
    read -p "The virtual environment '$VENV_DIR' already exists. Do you want to delete and recreate it? (y/n): " response
    if [[ "$response" =~ ^([yY][eE][sS]|[yY])$ ]]; then
        rm -rf "$VENV_DIR"
        echo -e "\e[31m[+]\e[0m \e[32mDirectory '$VENV_DIR' deleted.\e[0m"
    else
        echo -e "\e[31m[+]\e[0m \e[32mOperation canceled. The script will terminate.\e[0m"
        exit 1
    fi
fi

PYTHON_STABLE="/usr/bin/python3.12" 

if [ ! -f "$PYTHON_STABLE" ]; then
    PYTHON_STABLE="/usr/bin/python3"
fi

echo -e "\e[31m[+]\e[0m \e[32mCreating virtual environment using $PYTHON_STABLE\e[0m"
sudo -u "$REAL_USER" "$PYTHON_STABLE" -m venv "$VENV_DIR"


# Create the virtual environment using /usr/bin/python3 as REAL_USER
echo -e "\e[31m[+]\e[0m \e[32mCreating virtual environment '$VENV_DIR'\e[0m"
sudo -u "$REAL_USER" /usr/bin/python3 -m venv "$VENV_DIR"

# Upgrade pip & install packages using the venv's pip binary directly
echo -e "\e[31m[+]\e[0m \e[32mUpgrading pip & installing dependencies\e[0m"
sudo -u "$REAL_USER" "$VENV_DIR/bin/pip" install --upgrade pip setuptools wheel
sudo -u "$REAL_USER" "$VENV_DIR/bin/pip" install --prefer-binary pwntools ropper


echo -e "\e[31m[+]\e[0m \e[32mPhase 2 finished. Review logs to check for errors\e[0m"
read -p "Press [Enter] to continue..."


########################
# PHASE 3
########################
echo -e "\e[32m------------------------------------------------------\e[0m"
echo -e "\e[31m[+]\e[0m \e[32mStarting phase 3. Configuration of GDB and MSF\e[0m"
echo -e "\e[32m------------------------------------------------------\e[0m"
echo -e "\e[31m[+]\e[0m \e[32mInstalling GEF (GDB Enhanced Features)\e[0m"
sudo -u kali wget -O /home/kali/.gdbinit-gef.py https://gef.blah.cat/py~
sudo -u kali echo "source ~/.gdbinit-gef.py" > /home/kali/.gdbinit
# Now I add this to force visualization of the history in gdb and not allow gef to clear screen on each iteration
sudo -u kali echo "gef config context.clear_screen 0" >> home/kali/.gdbinit

echo -e "\e[31m[+]\e[0m \e[32mInstalling Framework2\e[0m"
apt install framework2


echo -e "\e[31m[+]\e[0m \e[32mPhase 3 finished. Review logs to check for errors\e[0m"
read -p "Press [Enter] to continue..."


########################
# PHASE 4
########################

echo -e "\e[32m------------------------------------------------------\e[0m"
echo -e "\e[31m[+]\e[0m \e[32mStarting phase 4. Disabling protections\e[0m"
echo -e "\e[32m------------------------------------------------------\e[0m"
# Finally, we disable ASLR protection
./disableASLR
echo -e "\e[31m[+]\e[0m \e[32mPhase 4 finished. Review logs to check for errors\e[0m"
